# baseurl: /

title: able99's dollhouse
desc: react love bnorth 《⊙＿⊙  home assistant is the third

sass:
  sass_dir: _sass
  style: compressed

permalink:
  none

types: 
  original: 
    title: '原创'
  
  link: 
    title: '链接'
  
  reproduce: 
    title: '转载'

mycategories:
  cuncategory:
    title: '随笔'
  cbnorth:
    title: '大前端开发套件 bnorth'
  
urls:
  bnorthGitPage: 'https://able99.github.io/bnorth/'

# svg editor https://svg-edit.github.io/svgedit/releases/svg-edit-2.8.1/svg-editor.html

markdown: kramdown
highlighter: rouge